server:
  port: 8990
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: bhavani
#    url: jdbc:mysql://localhost:2315/babudb
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    open-in-view: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
    password: babu

